import io
import re
import json
import math
import numpy as np
import pandas as pd
import streamlit as st

EXAMPLE_SURVEY = """
1.您的性别
A.男
B.女
2.您的年级
A.大一
B.大二
C.大三
3.您的生源地
A.城镇
B.农村
4.您是否担任班干部
A.是
B.否
5.您是否独生子女
A.独生子女
B.非独生子女
6.我有拖延症
A非常不符合
B不符合
C不确定
D符合
E非常符合
7.如果我有需要做的事，我会先做，而不是去做一些其他的事情
A非常不符合
B不符合
C不确定
D符合
E非常符合
"""

try:
    import pyreadstat
    HAS_PYREADSTAT = True
except Exception:
    HAS_PYREADSTAT = False

st.set_page_config(page_title="问卷解析 + 维度/关系约束 + SPSS数据生成器（本地网页）", layout="wide")


def parse_survey_text(txt: str):
    """解析问卷文本为题目列表"""
    lines = [l.strip() for l in txt.splitlines() if l.strip()]
    questions = []
    i = 0
    q_pat = re.compile(r"^(\d+)\s*[\.、]\s*(.+)$")
    opt_pat = re.compile(r"^([A-E])\s*[\.、]?\s*(.+)$")
    cur = None
    while i < len(lines):
        m = q_pat.match(lines[i])
        if m:
            if cur:
                questions.append(cur)
            cur = {"qid": int(m.group(1)), "stem": m.group(2).strip(), "options": {}}
            i += 1
            while i < len(lines) and not q_pat.match(lines[i]):
                om = opt_pat.match(lines[i])
                if om and cur is not None:
                    cur["options"][om.group(1)] = om.group(2).strip()
                i += 1
            continue
        i += 1
    if cur:
        questions.append(cur)

    for q in questions:
        opts = " ".join(q["options"].values())
        if any(k in opts for k in ["非常不符合", "不符合", "不确定", "符合", "非常符合"]):
            q["scale_type"] = "likert_fit"
        elif any(k in opts for k in ["同意", "较同意", "较不同意", "不同意"]):
            q["scale_type"] = "likert_agree"
        else:
            q["scale_type"] = "categorical"
    return questions


def generate_latents(n, dim_names, corr_matrix=None, seed=42):
    """生成大维度潜变量，带相关结构"""
    rng = np.random.default_rng(seed)
    k = len(dim_names)
    if corr_matrix is None:
        Z = rng.standard_normal(size=(n, k))
    else:
        R = np.array(corr_matrix, dtype=float)
        R = (R + R.T) / 2.0
        w, V = np.linalg.eigh(R)
        w[w < 1e-8] = 1e-8
        Rpsd = (V * w) @ V.T
        L = np.linalg.cholesky(Rpsd)
        Z = rng.standard_normal(size=(n, k)) @ L.T
    return pd.DataFrame(Z, columns=dim_names)


def apply_mediation(df_latents, A, C, B, a=0.6, b=0.6, cprime=0.1, seed=42):
    """中介模型：A -> C -> B"""
    rng = np.random.default_rng(seed)
    n = len(df_latents)
    eC = rng.standard_normal(n)
    var_eC = max(1e-6, 1.0 - a * a)
    df_latents[C] = a * df_latents[A] + math.sqrt(var_eC) * eC

    var_struct = b * b + cprime * cprime + 2 * a * b * cprime
    var_struct = max(0.0, min(var_struct, 1.0 - 1e-6))
    var_eB = max(1e-6, 1.0 - var_struct)
    eB = rng.standard_normal(n)
    df_latents[B] = b * df_latents[C] + cprime * df_latents[A] + math.sqrt(var_eB) * eB

    return df_latents


def latent_to_items(latent, n_items, mean=3.6, loading=1.0, noise=0.5, seed=42):
    """潜变量 → 1~5 李克特题目"""
    rng = np.random.default_rng(seed)
    cont = mean + loading * latent[:, None] + rng.standard_normal(size=(len(latent), n_items)) * noise
    return np.clip(np.rint(cont), 1, 5).astype(int)


def make_spss_syntax_for_csv(csv_filename, df_cols, var_labels, value_labels):
    """生成 SPSS 导入 + 标签语法"""
    var_lines = []
    for col in df_cols:
        if col == "ID":
            var_lines.append(f"{col} F8.0")
        else:
            var_lines.append(f"{col} F3.0")
    var_block = " \n  ".join(var_lines)

    vl = "\n".join([f"VARIABLE LABELS {k} '{v}'." for k, v in var_labels.items() if k in df_cols])

    blocks = []
    for var, mapping in value_labels.items():
        if var not in df_cols:
            continue
        parts = [f"{k} '{v}'" for k, v in mapping.items()]
        blocks.append(f"VALUE LABELS {var}\n  " + "\n  ".join(parts) + ".")
    vlab = "\n\n".join(blocks)

    return f"""* Auto-generated by Survey Synth WebApp.
GET DATA
  /TYPE=TXT
  /FILE='{csv_filename}'
  /ENCODING='UTF8'
  /DELCASE=LINE
  /DELIMITERS=","
  /QUALIFIER='"'
  /ARRANGEMENT=DELIMITED
  /FIRSTCASE=2
  /VARIABLES=
  {var_block}.
EXECUTE.

{vl}

{vlab}

EXECUTE.
"""


def _norm_cdf(x: float) -> float:
    """标准正态分布 CDF 近似，用于算 p 值（避免额外依赖）"""
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


# ---------- session_state 初始化 ----------
if "questions" not in st.session_state:
    st.session_state.questions = []
if "config" not in st.session_state:
    st.session_state.config = {}
if "raw_text" not in st.session_state:
    st.session_state.raw_text = ""

st.title("问卷解析 + 维度/关系约束 + SPSS数据生成器（本地网页）")
tabs = st.tabs(
    [
        "1) 导入/解析问卷",
        "2) 维度与计分 & 人口学",
        "3) 关系约束（人口学差异/相关/中介）",
        "4) 生成与导出",
    ]
)

# ---------- Tab 1: 导入/解析 ----------
with tabs[0]:
    st.subheader("粘贴问卷文本 → 自动识别题号/题干/选项")
    raw = st.text_area("问卷文本", value=st.session_state.get("raw_text", ""), height=320)
    c1, c2 = st.columns([1, 1])
    with c1:
        if st.button("解析问卷", type="primary", use_container_width=True):
            st.session_state.questions = parse_survey_text(raw)
            st.session_state.raw_text = raw
            st.success(f"已解析 {len(st.session_state.questions)} 道题。")
    with c2:
        if st.button("载入示例", use_container_width=True):
            st.session_state.raw_text = EXAMPLE_SURVEY
            st.session_state.questions = parse_survey_text(EXAMPLE_SURVEY)
            st.success(f"已载入示例并解析 {len(st.session_state.questions)} 道题。")

    if st.session_state.questions:
        dfq = pd.DataFrame(
            [
                {
                    "qid": q["qid"],
                    "scale_type": q["scale_type"],
                    "stem": q["stem"],
                    "options": " | ".join([f"{k}:{v}" for k, v in q["options"].items()]),
                }
                for q in st.session_state.questions
            ]
        ).sort_values("qid")
        st.dataframe(dfq, use_container_width=True)

# ---------- Tab 2: 维度、人 口学、题目参数 ----------
with tabs[1]:
    st.subheader("配置：维度归属、反向题、人口学 & 题目分布")
    qs = st.session_state.questions
    if not qs:
        st.info("先到第 1 页解析问卷。")
    else:
        # 所有题号
        all_qids = sorted([q["qid"] for q in qs])
        min_qid = min(all_qids)
        max_qid = max(all_qids)

        # 初始化默认 config
        if not st.session_state.config:
            # 默认起始题号：如果有第 6 题，就从 6；否则从最小题号
            default_start = 6 if any(q >= 6 for q in all_qids) else min_qid
            st.session_state.config = {
                "N": 630,
                "seed": 42,
                "scale_start_qid": default_start,
                "reverse_items": [],
                "dimensions": {
                    "A_dim": [q for q in all_qids if default_start <= q < default_start + 10],
                },
                # 小维度（按大维度划分），默认空
                "subdimensions": {},
                "demo": {
                    "use_Q1": False,
                    "use_Q2": False,
                    "use_Q3": False,
                    "use_Q4": False,
                    "use_Q5": False,
                    "Q1_perc": [50.0, 50.0],  # 男, 女
                    "grade_levels": 3,
                    "Q2_perc": [35.0, 40.0, 25.0],  # 年级
                    "Q3_perc": [55.0, 45.0],  # 城镇, 农村
                    "Q4_perc": [28.0, 72.0],  # 班干, 非班干
                    "Q5_perc": [38.0, 62.0],  # 独生, 非独生
                },
                "item_params": {
                    "mean": 3.60,
                    "loading": 0.80,
                    "noise": 0.75,
                },
                # 默认相关矩阵先留空，在 Tab3 按当前维度数量初始化
                "corr_matrix": None,
                "mediation": {
                    "A": "A_dim",
                    "C": "A_dim",
                    "B": "A_dim",
                    "a": 0.6,
                    "b": 0.6,
                    "cprime": 0.2,
                    "type": "部分中介",
                },
                # 每个维度上的人口学差异 β
                "demo_effects": {
                    "A_dim": {
                        "gender": 0.6,
                        "grade": 0.0,
                        "origin": 0.0,
                        "cadre": 0.0,
                        "only": 0.0,
                    },
                },
            }
        cfg = st.session_state.config

        # 样本量 & seed
        c1, c2 = st.columns([1, 1])
        with c1:
            cfg["N"] = st.number_input("样本量 N", 30, 5000, int(cfg.get("N", 630)), 10)
        with c2:
            cfg["seed"] = st.number_input("随机种子 seed", 0, 10000, int(cfg.get("seed", 42)), 1)

        # 量表维度起始题号（你可以自选从第几题开始）
        default_start_qid = int(cfg.get("scale_start_qid", 6))
        if default_start_qid < min_qid:
            default_start_qid = min_qid
        if default_start_qid > max_qid:
            default_start_qid = max_qid
        scale_start_qid = st.number_input(
            "量表维度起始题号（从这道题开始，后面的题才用于维度和 1~5 计分）",
            min_value=min_qid,
            max_value=max_qid,
            value=default_start_qid,
            step=1,
        )
        cfg["scale_start_qid"] = int(scale_start_qid)

        # 可作为维度题的题号
        scale_qids = [qid for qid in all_qids if qid >= cfg["scale_start_qid"]]

        # ------- 维度设置：多选题号 + 增删 -------
        st.markdown("### 大维度设置（大维度 = 若干题目的集合）")
        st.caption("每个维度下，直接多选题号；想删就点“删除本维度”，想加就点“➕ 新增维度”。")

        dims_dict = cfg.get("dimensions", {})
        dims_items = list(dims_dict.items())

        # 新增维度
        if st.button("➕ 新增维度"):
            base_name = "新维度"
            idx = 1
            new_name = base_name
            existing_names = set(dims_dict.keys())
            while new_name in existing_names:
                new_name = f"{base_name}{idx}"
                idx += 1
            dims_dict[new_name] = []
            cfg["dimensions"] = dims_dict
            st.session_state.config = cfg
            st.rerun()

        delete_keys = []
        for i, (orig_name, qid_list) in enumerate(dims_items):
            with st.expander(f"维度 {i+1}：{orig_name}", expanded=True):
                new_name = st.text_input("维度名称", value=orig_name, key=f"dim_name_{i}")
                valid_default = [qid for qid in qid_list if qid in scale_qids]
                selected_qids = st.multiselect(
                    "包含题目（可多选）",
                    options=scale_qids,
                    default=valid_default,
                    key=f"dim_items_{i}",
                )
                if st.button("删除本维度", key=f"dim_del_{i}"):
                    delete_keys.append(orig_name)

        if delete_keys:
            for k in delete_keys:
                if k in dims_dict:
                    dims_dict.pop(k)
            cfg["dimensions"] = dims_dict
            st.session_state.config = cfg
            st.rerun()
        else:
            # 修复“新增维度有时加不上”的问题：只要有名字就保留，题目可以暂时为空
            new_dims = {}
            for i, (orig_name, qid_list) in enumerate(dims_items):
                name = st.session_state.get(f"dim_name_{i}", "").strip() or orig_name
                items = st.session_state.get(f"dim_items_{i}", None)
                if items is None:
                    items = qid_list
                if name:
                    new_dims[name] = sorted(set(items))
            cfg["dimensions"] = new_dims

        if not cfg["dimensions"]:
            st.warning("当前还没有任何维度，请点击“➕ 新增维度”创建。")
        else:
            st.success(f"当前共有 {len(cfg['dimensions'])} 个大维度。")

        # ------- 小维度设置 -------
        st.markdown("### 小维度设置（可选，大维度内部再分）")
        st.caption(
            "每个大维度下可以再划分若干小维度。每行格式：小维度名称:题号,题号,题号\n"
            "支持中英文冒号/逗号；小维度的题目必须是该大维度内已有的题目，否则会被忽略。"
        )

        subdims_all = cfg.get("subdimensions", {})
        if not isinstance(subdims_all, dict):
            subdims_all = {}

        new_subdims_all = {}

        for big_dim, qids_big in cfg["dimensions"].items():
            with st.expander(f"大维度「{big_dim}」的小维度设置", expanded=False):
                exist_sub = subdims_all.get(big_dim, {})
                lines = []
                for sub_name, qids in exist_sub.items():
                    if not qids:
                        continue
                    line = f"{sub_name}:{','.join(str(q) for q in qids)}"
                    lines.append(line)
                default_text = "\n".join(lines)
                txt = st.text_area(
                    "每行一个小维度（示例：行为拖延:6,7,8,9,10）",
                    value=default_text,
                    key=f"subdim_text_{big_dim}",
                    height=120,
                )

                sub_dict = {}
                for line in txt.splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    line = line.replace("：", ":").replace("，", ",")
                    if ":" not in line:
                        continue
                    name_part, q_part = line.split(":", 1)
                    sub_name = name_part.strip()
                    if not sub_name:
                        continue
                    q_tokens = [t.strip() for t in q_part.split(",") if t.strip()]
                    qid_list_tmp = []
                    for token in q_tokens:
                        if token.isdigit():
                            q_val = int(token)
                            if q_val in qids_big:
                                qid_list_tmp.append(q_val)
                    if qid_list_tmp:
                        sub_dict[sub_name] = sorted
