import io
import re
import json
import math
import numpy as np
import pandas as pd
import streamlit as st

EXAMPLE_SURVEY = """
1.您的性别
A.男
B.女
2.您的年级
A.大一
B.大二
C.大三
3.您的生源地
A.城镇
B.农村
4.您是否担任班干部
A.是
B.否
5.您是否独生子女
A.独生子女
B.非独生子女
6.我有拖延症
A非常不符合
B不符合
C不确定
D符合
E非常符合
7.如果我有需要做的事，我会先做，而不是去做一些其他的事情
A非常不符合
B不符合
C不确定
D符合
E非常符合
"""

try:
    import pyreadstat
    HAS_PYREADSTAT = True
except Exception:
    HAS_PYREADSTAT = False

st.set_page_config(page_title="问卷解析 + 维度/关系约束 + SPSS数据生成器（本地网页）", layout="wide")


def parse_survey_text(txt: str):
    lines = [l.strip() for l in txt.splitlines() if l.strip()]
    questions = []
    i = 0
    q_pat = re.compile(r"^(\d+)\s*[\.、]\s*(.+)$")
    opt_pat = re.compile(r"^([A-E])\s*[\.、]?\s*(.+)$")
    cur = None
    while i < len(lines):
        m = q_pat.match(lines[i])
        if m:
            if cur:
                questions.append(cur)
            cur = {"qid": int(m.group(1)), "stem": m.group(2).strip(), "options": {}}
            i += 1
            while i < len(lines) and not q_pat.match(lines[i]):
                om = opt_pat.match(lines[i])
                if om and cur is not None:
                    cur["options"][om.group(1)] = om.group(2).strip()
                i += 1
            continue
        i += 1
    if cur:
        questions.append(cur)

    for q in questions:
        opts = " ".join(q["options"].values())
        if any(k in opts for k in ["非常不符合", "不符合", "不确定", "符合", "非常符合"]):
            q["scale_type"] = "likert_fit"
        elif any(k in opts for k in ["同意", "较同意", "较不同意", "不同意"]):
            q["scale_type"] = "likert_agree"
        else:
            q["scale_type"] = "categorical"
    return questions


def generate_latents(n, dim_names, corr_matrix=None, seed=42):
    rng = np.random.default_rng(seed)
    k = len(dim_names)
    if corr_matrix is None:
        Z = rng.standard_normal(size=(n, k))
    else:
        R = np.array(corr_matrix, dtype=float)
        R = (R + R.T) / 2.0
        w, V = np.linalg.eigh(R)
        w[w < 1e-8] = 1e-8
        Rpsd = (V * w) @ V.T
        L = np.linalg.cholesky(Rpsd)
        Z = rng.standard_normal(size=(n, k)) @ L.T
    return pd.DataFrame(Z, columns=dim_names)


def apply_mediation(df_latents, A, C, B, a=0.6, b=0.6, cprime=0.1, seed=42):
    rng = np.random.default_rng(seed)
    n = len(df_latents)
    eC = rng.standard_normal(n)
    var_eC = max(1e-6, 1.0 - a * a)
    df_latents[C] = a * df_latents[A] + math.sqrt(var_eC) * eC

    var_struct = b * b + cprime * cprime + 2 * a * b * cprime
    var_struct = max(0.0, min(var_struct, 1.0 - 1e-6))
    var_eB = max(1e-6, 1.0 - var_struct)
    eB = rng.standard_normal(n)
    df_latents[B] = b * df_latents[C] + cprime * df_latents[A] + math.sqrt(var_eB) * eB

    return df_latents


def latent_to_items(latent, n_items, mean=3.6, loading=1.0, noise=0.5, seed=42):
    rng = np.random.default_rng(seed)
    cont = mean + loading * latent[:, None] + rng.standard_normal(size=(len(latent), n_items)) * noise
    return np.clip(np.rint(cont), 1, 5).astype(int)


def make_spss_syntax_for_csv(csv_filename, df_cols, var_labels, value_labels):
    var_lines = []
    for col in df_cols:
        if col == "ID":
            var_lines.append(f"{col} F8.0")
        else:
            var_lines.append(f"{col} F3.0")
    var_block = " \n  ".join(var_lines)

    vl = "\n".join([f"VARIABLE LABELS {k} '{v}'." for k, v in var_labels.items() if k in df_cols])

    blocks = []
    for var, mapping in value_labels.items():
        if var not in df_cols:
            continue
        parts = [f"{k} '{v}'" for k, v in mapping.items()]
        blocks.append(f"VALUE LABELS {var}\n  " + "\n  ".join(parts) + ".")
    vlab = "\n\n".join(blocks)

    return f"""* Auto-generated by Survey Synth WebApp.
GET DATA
  /TYPE=TXT
  /FILE='{csv_filename}'
  /ENCODING='UTF8'
  /DELCASE=LINE
  /DELIMITERS=","
  /QUALIFIER='"'
  /ARRANGEMENT=DELIMITED
  /FIRSTCASE=2
  /VARIABLES=
  {var_block}.
EXECUTE.

{vl}

{vlab}

EXECUTE.
"""


def _norm_cdf(x: float) -> float:
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


if "questions" not in st.session_state:
    st.session_state.questions = []
if "config" not in st.session_state:
    st.session_state.config = {}
if "raw_text" not in st.session_state:
    st.session_state.raw_text = ""

st.title("问卷解析 + 维度/关系约束 + SPSS数据生成器（本地网页）")
tabs = st.tabs(
    [
        "1) 导入/解析问卷",
        "2) 维度与计分 & 人口学",
        "3) 关系约束（人口学差异/相关/中介）",
        "4) 生成与导出",
    ]
)

with tabs[0]:
    st.subheader("粘贴问卷文本 → 自动识别题号/题干/选项")
    raw = st.text_area("问卷文本", value=st.session_state.get("raw_text", ""), height=320)
    c1, c2 = st.columns([1, 1])
    with c1:
        if st.button("解析问卷", type="primary", use_container_width=True):
            st.session_state.questions = parse_survey_text(raw)
            st.session_state.raw_text = raw
            st.success(f"已解析 {len(st.session_state.questions)} 道题。")
    with c2:
        if st.button("载入示例", use_container_width=True):
            st.session_state.raw_text = EXAMPLE_SURVEY
            st.session_state.questions = parse_survey_text(EXAMPLE_SURVEY)
            st.success(f"已载入示例并解析 {len(st.session_state.questions)} 道题。")

    if st.session_state.questions:
        dfq = pd.DataFrame(
            [
                {
                    "qid": q["qid"],
                    "scale_type": q["scale_type"],
                    "stem": q["stem"],
                    "options": " | ".join([f"{k}:{v}" for k, v in q["options"].items()]),
                }
                for q in st.session_state.questions
            ]
        ).sort_values("qid")
        st.dataframe(dfq, use_container_width=True)

# 维度设置，人口学设置和数据生成（这部分代码需要继续调整）
